config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  get "setup_tokens/index"
  get "setup_tokens/create"
  get "setup_tokens/delete"

  get "setup", to: "setup#index", as: :setup
  post "setup/save", to: "setup#save", as: :save_setup

  resources :setup_tokens, only: [:index, :create, :destroy]

  resources :users
  get "activate/:code", to: "users#activate", as: :user_activation
  post "users/create-from-activation", to: "users#create_from_activation", as: :users_activation_path

  resources :sessions, only: %i[new create destroy]

  get "games/list", to: "games#list", as: :games_list

  resources :games do
    patch "current-context", to: "games/current_context#update", as: :update_context
    get "current-context/edit", to: "games/current_context#edit", as: :edit_context

    patch "host/online", to: "games/host#online"
    patch "host/offline", to: "games/host#offline"
    patch "host/typing", to: "games/host#typing"
    patch "host/stop-typing", to: "games/host#stop_typing"
  end

  get "games/:id/lobby", to: "games#lobby", as: :game_lobby
  patch "games/:id/join", to: "games#join", as: :join_game

  patch "game_users/:id/online", to: "game_users#online"
  patch "game_users/:id/offline", to: "game_users#offline"
  patch "game_users/:id/typing", to: "game_users#typing"
  patch "game_users/:id/stop-typing", to: "game_users#stop_typing"
  patch "game_users/:id", to: "game_users#update", as: :game_user
  patch "game_users/:game_id/mute-or-unmute", to: "game_users#mute_or_unmute_all_players", as: :game_users_mute_or_unmute

  get "messages", to: "messages#index", as: :messages
  post "messages", to: "messages#create", as: :create_message
  get "messages/create"

  get "signup", to: "users#new", as: :signup
  get "login", to: "sessions#new", as: :login
  get "logout", to: "sessions#destroy", as: :logout

  get "tavern", to: "games#index", as: :tavern

  get "about", to: "about#index"

  get "generate-text", to: "generate_text#text"
end

app/models/setup_token.rb
# frozen_string_literal: true

class SetupToken < ApplicationRecord
  belongs_to :user, optional: true

  before_create :set_uuid

  scope :active, -> { where(user_id: nil) }

  def active?
    user_id.nil?
  end

  private

    def set_uuid
      self.uuid = SecureRandom.uuid
    end
end

app/controllers/setup_tokens_controller.rb
# frozen_string_literal: true

class SetupTokensController < ApplicationController
  authorize_resource

  def index
    @tokens = SetupToken.all
  end

  def create
    token = SetupToken.create!

    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.append(:setup_tokens, partial: "setup_tokens/setup_token",
                                                                locals: { token: token })
      end
    end
  end

  def destroy
    token = SetupToken.find(params[:id])
    token.destroy
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.remove(token)
      end
    end
  end
end

app/views/setup_tokens/_setup_token.html.erb
<div class="w-full border-b-2 border-terminal-green flex items-center py-5 gap-5" id="<%= dom_id(token) %>">
  <% if token.active? %>
    <div class="whitespace-nowrap"><span class="text-sm"><%= user_activation_url(code: token.uuid) %></span></div>
    <div>
      <div class="button" data-controller="copy" data-copy-text-value="<%= user_activation_url(code: token.uuid) %>" data-action="click->copy#to_clipboard">Copy</div>
    </div>
    <div>
      <%= form_with(url: setup_token_path(id: token), method: :delete) do |f| %>
        <%= f.submit class: "button", value: "Delete" %>
      <% end %>
    </div>
  <% else %>
    <div class="text-center w-full">
      Token redeemed by user "<span class="underline font-bold"><%= token.user.username %></span>" on <%= token.updated_at.strftime("%m/%d/%Y") %> at <%= token.updated_at.strftime("%I:%M%p") %>
    </div>
  <% end %>
</div>

app/views/setup_tokens/index.html.erb
<h3 class="text-center my-5 text-2xl">Token Management</h3>

<%= render(NoticeComponent.new(message: notice)) %>

<p class="mb-6">Here you can generate links to send to your friends. This will allow them to create a username and a password and join your game(s).</p>

<%= form_with(model: SetupToken.new, class: "py-5") do |f| %>
  <%= f.submit class: "button w-full" %>
<% end %>

<div class="border-t-2 border-dashed border-terminal-green pt-5 px-2">
  <%= turbo_frame_tag(:setup_tokens) do %>
    <% @tokens.each do |token| %>
      <%= render "setup_token", token: token %>
    <% end %>
  <% end %>
</div>

<% content_for :sidebar do %>
  <%= ascii("bricks") %>
<% end %>