config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  get "setup_tokens/index"
  get "setup_tokens/create"
  get "setup_tokens/delete"

  get "setup", to: "setup#index", as: :setup
  post "setup/save", to: "setup#save", as: :save_setup

  resources :setup_tokens, only: [:index, :create, :destroy]

  resources :users
  get "activate/:code", to: "users#activate", as: :user_activation
  post "users/create-from-activation", to: "users#create_from_activation", as: :users_activation_path

  resources :sessions, only: %i[new create destroy]

  get "games/list", to: "games#list", as: :games_list

  resources :games do
    patch "current-context", to: "games/current_context#update", as: :update_context
    get "current-context/edit", to: "games/current_context#edit", as: :edit_context

    patch "host/online", to: "games/host#online"
    patch "host/offline", to: "games/host#offline"
    patch "host/typing", to: "games/host#typing"
    patch "host/stop-typing", to: "games/host#stop_typing"
  end

  get "games/:id/lobby", to: "games#lobby", as: :game_lobby
  patch "games/:id/join", to: "games#join", as: :join_game

  patch "game_users/:id/online", to: "game_users#online"
  patch "game_users/:id/offline", to: "game_users#offline"
  patch "game_users/:id/typing", to: "game_users#typing"
  patch "game_users/:id/stop-typing", to: "game_users#stop_typing"
  patch "game_users/:id", to: "game_users#update", as: :game_user
  patch "game_users/:game_id/mute-or-unmute", to: "game_users#mute_or_unmute_all_players", as: :game_users_mute_or_unmute

  get "messages", to: "messages#index", as: :messages
  post "messages", to: "messages#create", as: :create_message
  get "messages/create"

  get "signup", to: "users#new", as: :signup
  get "login", to: "sessions#new", as: :login
  get "logout", to: "sessions#destroy", as: :logout

  get "tavern", to: "games#index", as: :tavern

  get "about", to: "about#index"

  get "generate-text", to: "generate_text#text"
end

app/models/game.rb
# frozen_string_literal: true

class Game < ApplicationRecord
  CHATGPT_SYSTEM_PROMPT = <<-PROMPT
  You are acting as the text-parser in a text-based adventure game.
  As the game, you will create a dynamic and engaging world, describe the environment,
  control non-player characters (NPCs),
  and narrate the outcomes of players' actions.
  Keep all responses brief and minimal.
  Your goal is to provide a fun and immersive experience, while ensuring that you follow the rules of the game and maintain a fair and balanced play environment.
  If a player asks to do something, ask them to make an appropriate ability with a dice roll.
  There are no player modifiers.
  If you ask a player to make a roll, and they do not respond with a number or a valid roll, admonish them and ask for the roll again.
  Don't make assumptions about what values to plug into functions. Ask for clarification if a user request is ambiguous.
  Do not tell the players what they are doing, ask them what they would like to do.
  PROMPT

  MAX_TOKENS_FOR_AI_CHAPTER = 7500

  belongs_to :host, class_name: "User",
                    foreign_key: :created_by,
                    primary_key: :id,
                    dependent: :destroy,
                    inverse_of: :hosted_games,
                    optional: true

  has_many :game_users, inverse_of: :game, dependent: :destroy
  has_many :users, through: :game_users

  has_many :chapters, inverse_of: :game, dependent: :destroy

  has_many :messages, inverse_of: :game, dependent: :destroy

  scope :joinable_by_user, ->(user) { where(status: :open).where.not(created_by: user.id) }

  before_create :set_uuid

  after_save :broadcast_context, if: :saved_change_to_current_context?

  after_create_commit :setup_ai, if: proc { game_type == "chatgpt" }

  validates :created_by, presence: true

  def complete_chapters
    chapters.order(:id).where.not(last_message_id: nil)
  end

  def current_chapter
    chapters.where(last_message_id: nil).last
  end

  def current_messages
    messages.where("id > ?", current_chapter&.first_message_id || 0)
  end

  def current_token_count
    TOKENIZER.encode(messages_for_ai.select { |m| m[:content] }.join).tokens.count
  end

  def game_user(user)
    game_users.find_by(user_id: user.id)
  end

  def host?(user)
    return false if game_type == "chatgpt"

    created_by == user&.id
  end

  def user_in_game?(user)
    game_users.pluck(:user_id).include?(user.id)
  end

  def can_user_join?(user)
    !user_in_game?(user) && !host?(user) && !max_players?
  end

  def max_players?
    game_users.count == max_players
  end

  def role_for_ai_message(message)
    role = "user" if message.player_message?
    role = "assistant" if message.host_message?
    role = "system" if message.is_system_message?
    role
  end

  def messages_for_ai
    chat_log_for_ai = [
      { role: "system", content: "#{CHATGPT_SYSTEM_PROMPT} The name of this D&D campaign is #{name}." }
    ]

    chat_log_for_ai += chapter_summaries

    current_messages.for_ai.each do |m|
      next if m.event?

      content = if m.player_message?
                  "[#{m.display_name}] #{m.content}"
                elsif m.event_type == "roll"
                  m.roll_result_message_for_ai
                else
                  m.content
                end

      chat_log_for_ai << { role: role_for_ai_message(m), content: content }
    end
    chat_log_for_ai
  end

  def chapter_summaries
    summaries = []
    if complete_chapters.present?
      complete_chapters.each do |chapter|
        summaries << {
          role: "assistant", content: "#{chapter.name} #{chapter.summary}"
        }
      end
    end
    summaries
  end

  def broadcast_updated_player_list
    broadcast_replace_to(self, :players, target: :players, partial: "/games/players",
                                         locals: { game_users: game_users.joined, for_host: false })
  end

  private

    def set_uuid
      self.uuid = SecureRandom.uuid
    end

    def broadcast_context
      broadcast_replace_to(self, :state, target: :context_content, partial: "/games/current_context",
                                         locals: { game: self })
    end

    def setup_ai
      client = OpenAI::Client.new

      chat_log = messages_for_ai
      chat_log << { role: "user",
                    content: <<-INSTRUCTION
                    Please create a very brief description of the game world. No players have joined yet.
                    Also describe the opening scene the players will once they join the game.
                    INSTRUCTION
                  }
      response = client.chat(parameters: { model: "gpt-4o", messages: chat_log })
      ai_response = response.dig("choices", 0, "message", "content")

      message = Message.create(game_id: id, content: ai_response)

      Chapter.create(game_id: id, number: 1, first_message_id: message.id)
    end
end

app/controllers/games/current_context_controller.rb
# frozen_string_literal: true

module Games
  class CurrentContextController < ApplicationController
    before_action :set_game

    def edit
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(:context, template: "games/current_context/edit")
        end
        format.html
      end
    end

    def update
      respond_to do |format|
        if @game.update(current_context_params)
          format.turbo_stream do
            render turbo_stream: turbo_stream.replace(:context, partial: "games/current_context",
                                                                locals: { game: @game })
          end
        else
          format.html { render :edit, status: :unprocessable_entity }
          format.json { render json: @game.errors, status: :unprocessable_entity }
        end
      end
    end

    private

      def set_game
        @game = Game.where(id: params[:game_id]).or(Game.where(uuid: params[:game_id])).first!
      end

      def current_context_params
        params.require(:game).permit(:current_context, :is_current_context_ascii)
      end
  end
end

app/controllers/games/host_controller.rb
# frozen_string_literal: true

module Games
  class HostController < ApplicationController
    before_action :authorize!
    before_action :set_game

    def online
      @game.update(is_host_online: true, host_online_at: DateTime.now)
      head :ok
    end

    def offline
      @game.update(is_host_online: false, is_typing: false)
      head :ok
    end

    def typing
      @game.update(is_host_typing: true, host_typing_at: DateTime.now)
      head :ok
    end

    def stop_typing
      @game.update(is_host_typing: false)
      head :ok
    end

    private

      def set_game
        @game = Game.where(id: params[:game_id]).or(Game.where(uuid: params[:game_id])).first!
      end
  end
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  load_resource find_by: :uuid
  authorize_resource

  before_action :set_turbo_frame_id
  before_action :set_game, except: %i[index list new create]
  before_action :load_games, only: %i[index list]

  def index; end

  def list
    respond_to do |format|
      format.turbo_stream { render turbo_stream: turbo_stream.update(@turbo_frame_id, partial: "list") }
      format.html
    end
  end

  # rubocop:disable Metrics/MethodLength
  def join
    authorize! :join, @game

    @game.with_lock do
      if @game.can_user_join?(current_user)
        game_user_params = {
          user_id: current_user.id,
          character_name: params[:character_name],
          character_description: params[:character_description]
        }

        @game_user = @game.game_users.create(game_user_params)
      end

      @game.update(status: :closed) if @game_user.valid? && @game.max_players?
    end

    respond_to do |format|
      if @game_user.valid?
        format.html { redirect_to game_url(id: @game.uuid), notice: t(:ye_joined) }
      else
        format.html { redirect_to tavern_url, notice: t(:join_failed) }
      end
    end
  end
  # rubocop:enable Metrics/MethodLength

  def lobby
    authorize! :lobby, @game
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update(@turbo_frame_id, partial: "lobby")
      end
      format.html
    end
  end

  def show
    if @game.host?(current_user)
      @game.update(host_active_at: DateTime.now)
    else
      @game.game_user(current_user).update(active_at: DateTime.now)
    end

    @pagy, @messages = pagy(Message.for_game(@game), items: 10)
  end

  def new
    @game = Game.new(created_by: current_user.id)
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update(@turbo_frame_id, partial: "games/form", locals: { game: @game })
      end
    end
  end

  def edit
    respond_to do |format|
      format.turbo_stream do
        render turbo_stream: turbo_stream.update(@turbo_frame_id, partial: "games/form", locals: { game: @game })
      end
      format.html
    end
  end

  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        if @game.game_type == "chatgpt"
          format.html { redirect_to tavern_url, notice: t(:game_created_successfully) }
        else
          format.html { redirect_to game_url(@game) }
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @game.update(game_params)
        format.turbo_stream { render turbo_stream: turbo_stream.update(@turbo_frame_id, template: "games/show") }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url, notice: t(:game_destroyed) }
      format.json { head :no_content }
    end
  end

  private

    def load_games
      @hosted_games = current_user.hosted_games.load_async
      @joined_games = current_user.joined_games.load_async
      @joinable_games = Game.joinable_by_user(current_user).where.not(id: @joined_games.ids).load_async
    end

    def set_game
      @game = Game.where(id: params[:id]).or(Game.where(uuid: params[:id])).first!
    end

    def game_params
      params.require(:game).permit(:uuid, :name, :game_type, :created_by, :status, :opened_at, :closed_at,
                                   :is_friends_only, :max_players, :description, :host_display_name,
                                   :current_context, :is_current_context_ascii, :enable_hp, :starting_hp)
    end

    def set_turbo_frame_id
      @turbo_frame_id = params[:turbo_frame_id].presence&.to_sym || :sidebar
    end
end

app/helpers/games_helper.rb
# frozen_string_literal: true

module GamesHelper
  def game_type_options
    [
      %w[Free-Form freeform],
      %w[ChatGPT chatgpt]
    ]
  end

  def game_status_options
    [
      %w[Open open],
      %w[Closed closed]
    ]
  end
end

app/views/games/_current_context.html.erb
<%= turbo_frame_tag(:context) do %>
  <%= turbo_frame_tag(:context_content) do %>
    <div class="text-center border-double border-8 border-terminal-green py-2 px-1 overflow-x-auto terminal-scrollbars">
      <% if game.current_context.present? %>
        <% if game.is_current_context_ascii?  %>
          <pre class="text-xs">
            <%= game.current_context.html_safe %>
          </pre>
        <% else %>
          <p><%= game.current_context %></p>
        <% end %>
      <% else %>
        <%= game.description %>
      <% end %>
    </div>
  <% end %>
  <% if game.host?(current_user) %>
    <div class="text-center mt-2">
      <%= link_to "Change Text/ASCII Art", game_edit_context_path(game_id: game.id), class: "button is-small", data: {"turbo-frame": "context"}, remote: true %>
    </div>
  <% end %>
<% end %>

app/views/games/_form.html.erb
<%= form_with(model: game, data: { "turbo-frame": "_top" }) do |form| %>
  <%= form.hidden_field :created_by %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>
      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="form-group">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div class="form-group">
    <%= form.label :host_display_name, style: "display: block" %>
    <%= form.text_field :host_display_name, value: game.host_display_name || "Game Master" %>
  </div>

  <div class="form-group">
    <%= form.label :game_type, style: "display: block" %>
    <%= form.select :game_type, options_for_select(game_type_options, "freeform") %>
  </div>

  <div class="form-group">
    <%= form.label :status, style: "display: block" %>
    <%= form.select :status, options_for_select(game_status_options, "closed") %>
  </div>

  <div class="form-group" style="display: none;">
    <%= form.label :is_friends_only do %>
      Friends Only?
    <% end %>
    <%= form.check_box :is_friends_only %>
  </div>

  <div class="form-group">
    <%= form.label :enable_hp do %>
      Enable HP
    <% end %>
    <%= form.check_box :enable_hp %>
  </div>

  <div class="form-group">
    <%= form.label :starting_hp, style: "display: block" %>
    <%= form.number_field :starting_hp, { value: (game.starting_hp || 10), min: 1 } %>
  </div>

  <div class="form-group">
    <%= form.label :max_players, style: "display: block" %>
    <%= form.number_field :max_players, { value: (game.max_players || 4), max: 5, min: 1 } %>
  </div>

  <div>
    <%= form.submit class: "button mt-5 mx-auto" %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>">
  <p>
    <strong>Uuid:</strong>
    <%= game.uuid %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= game.name %>
  </p>

  <p>
    <strong>Game type:</strong>
    <%= game.game_type %>
  </p>

  <p>
    <strong>Created by:</strong>
    <%= game.created_by %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= game.status %>
  </p>

  <p>
    <strong>Opened at:</strong>
    <%= game.opened_at %>
  </p>

  <p>
    <strong>Closed at:</strong>
    <%= game.closed_at %>
  </p>

  <p>
    <strong>Is friends only:</strong>
    <%= game.is_friends_only %>
  </p>

  <p>
    <strong>Max players:</strong>
    <%= game.max_players %>
  </p>

</div>

app/views/games/_game_list_card.html.erb
<div id="table-join-element-<%= game_number %>" data-game-id="<%= game.uuid %>">
  <div class="title"><strong>#<%= game_number %></strong> <%= game.name %></div>
  <% if game.description %>
    <div class="description">&gt; <em><%= game.description %></em></div>
  <% end %>
</div>

app/views/games/_list.html.erb
<% if @hosted_games.blank? && @joined_games.blank? && @joinable_games.blank? %>

  <h3 class="text-center mb-0">Tables</h3>
  <p class="text-center">** NO OPEN TABLES **</p>

<% else %>
  <% game_counter = 1 %>
  <div id="games">
    <% { hosted: @hosted_games, joined: @joined_games, joinable: @joinable_games }.each do |type, games| %>
      <% if games.present? %>
        <h3 class="text-center mb-0"><%= type.to_s.titleize %> Tables</h3>

        <% games.each do |game| %>
          <%= render "/games/game_list_card", game: game, game_number: game_counter %>
          <% game_counter += 1 %>
        <% end %>
      <% end %>
    <% end %>
  </div>

<% end %>

app/views/games/_lobby.html.erb
<div class="m-2 p-3 border-2 border-solid border-terminal-green">
  <h3 class="text-center text-xl"><%= @game.name %></h3>
  <p class="text-center mt-2 mb-5"><%= @game.description %></p>

  <p>Host: <strong><%= @game.host.username %></strong></p>
  <p>Players: <strong><%= @game.game_users.count %> / <%= @game.max_players %></strong></p>
  <p class="mb-2">Type: <strong><%= @game.game_type.titleize %></strong></p>

  <% if @game.can_user_join?(current_user) %>
    <h3 class="text-center">Join Game</h3>
    <%= form_with(url: join_game_path(id: @game.uuid), method: :patch, data: { "turbo-frame": "_top" }) do |form| %>
      <%= form.hidden_field :user_id, value: current_user.id %>

      <div class="form-group">
        <%= form.label :character_name, style: "display: block" %>
        <%= form.text_field :character_name %>
      </div>

      <% if @game.game_type == "chatgpt" %>
        <div class="form-group">
          <%= form.label :character_description, style: "display: block" %>
          <%= form.text_area :character_description %>
        </div>
      <% end %>

      <div class="text-center w-full">
        <%= form.submit class: "button w-full", value: "Join Table" %>
      </div>
    <% end %>
  <% elsif(@game.user_in_game?(current_user) || @game.host?(current_user)) %>
    <div class="text-center w-full mt-5">
      <%= link_to "Rejoin Game", game_path(id: @game.uuid), id: "game-join-element", class: "button w-full", data: { "turbo-frame": "_top", "uuid": @game.uuid } %>
    </div>
  <% else %>
    <p class="text-center"><strong>Ye mayn't join, m'lord.</strong></p>
  <% end %>
</div>

app/views/games/_player.html.erb
<%= tag.li id: dom_id(game_user), class: classes("mb-5 leading-3 whitespace-nowrap game-user", "cursor-pointer": for_host), data: { controller: "game-user", action: "click->game-user#health_form", "game-user-muted-value": !game_user.can_message, "game-user-id-value": game_user.id } do %>
	<span class="<%= classes("opacity-50": !game_user.can_message) %>"><%= game_user.character_name %></span>
	<% if game_user.game.enable_hp? %>
		<span class="font-medium text-sm nowr">(<%= game_user.current_health %>/<%= game_user.max_health %>)</span><br>
	  <span class="text-xs font-italic ml-10">Active <%= game_user.active_at&.strftime("%a %b %e %r") %></span>
		<% if for_host %>
			<div class="fixed inset-0 z-10 overflow-y-auto bg-stone-800 bg-opacity-25 hidden" data-game-user-target="healthForm">
				<div class="flex min-h-full items-end justify-center sm:items-center">
					<%= form_with(model: game_user, url: game_user_path(id: game_user), method: :patch, class: "bg-stone-900 shadow-[-20px_25px_0px_0px_#000000] border-terminal-green border-dashed border-2 p-5", data: { "turbo-frame": "player" }) do |form| %>
					  <div class="mb-3">
					    <%= form.label :heal, class: "block uppercase mb-3", min: 0 %>
					    <%= form.number_field :heal %>
					  </div>

					  <div class="mb-3">
					    <%= form.label :damage, class: "block uppercase mb-3", min: 0 %>
					    <%= form.number_field :damage %>
					  </div>

					  <div class="mb-3">
					  	<label for="can_message">Mute</label>
					    <%= form.check_box :can_message, { checked: !game_user.can_message }, false, true %>
					  </div>

					  <div class="grid grid-cols-2 mt-5">
					    <%= form.submit class: "button p-3", value: "APPLY" %>
					    <button class="button border-red-500 text-red-500 hover:text-red-100 hover:border-red-900 hover:bg-red-900 p-3" data-action="click->game-user#close_health_form" type="button">Cancel</button>
					  </div>
					<% end %>
				</div>
			</div>
		<% end %>
	<% end %>
<% end %>

app/views/games/_players.html.erb
<%= turbo_frame_tag(:players) do %>
  <ul class="list-square list-inside">
    <% game_users.each do |game_user| %>
      <%= render "/games/player", game_user: game_user, for_host: for_host %>
    <% end %>
  </ul>
<% end %>

app/views/games/edit.html.erb
<turbo-frame id="<%= @turbo_frame_id %>">
  <h1>Editing game</h1>

  <%= render "form", game: @game %>

  <br>

  <div>
    <%= link_to "Show this game", @game %> |
    <%= link_to "Back to games", games_path %>
  </div>
</turbo-frame>

app/views/games/index.html.erb
<h3 class="text-center mb-0">Ye Olde Tavern</h3>
<%= ascii("tavern") %>
<p class="mb-0 mt-2">You see many tables. Some contain adventurers. Others sit empty.</p>
<p class="mb-0">You may...</p>
<ul>
  <li><strong>LIST TABLES</strong> to see a list of joinable games</li>
  <li><strong>NEW TABLE</strong> to start a new adventure</li>
  <li><strong>JOIN TABLE &lt;#&gt;</strong> to join a game</li>
</ul>

<% content_for :text_form do %>
  <%= render "/shared/terminal_input", prompt: "Tavern", controllers: ["tavern"] %>
<% end %>

<% content_for :sidebar do %>
  <% if notice %>
    <div class="notice blink text-center"><%= notice %></div>
  <% end %>
  <%= render template: "/games/list" %>
<% end %>

app/views/games/list.html.erb
<turbo-frame id="<%= @turbo_frame_id %>">
  <%= render "/games/list" %>
</turbo-frame>

app/views/games/lobby.html.erb
<turbo-frame id="<%= @turbo_frame_id %>">
  <%= render "/games/lobby" %>
</turbo-frame>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/show.html.erb
<%= turbo_stream_from(@game, :messages) %>
<%= turbo_stream_from(@game, :state) %>
<% if @game.host?(current_user) %>
  <%= turbo_stream_from(@game, :host_players) %>
<% else %>
  <%= turbo_stream_from(@game, :players) %>
<% end %>

<div id="message-content-wrapper" class="invisible">
  <%= render "/messages/pager", game: @game, pagy: @pagy %>

  <div id="game-messages" class="relative">
    <%= turbo_frame_tag(:messages) do %>
      <% @messages.reverse.each do |message| %>
        <%= render "/messages/message", message: message %>
      <% end %>
    <% end %>
  </div>
</div>

<% content_for :text_form do %>
  <%= render(TerminalInputComponent.new(prompt: "", stimulus_controllers: ["game"], stimulus_values: { "game-id": @game.id, "game-user-id": @game.host?(current_user) ? :host : @game.game_user(current_user)&.id })) %>
<% end %>

<% content_for :sidebar do %>
  <h3 class="text-center mb-2"><strong><%= @game.name %></strong></h3>
  
  <div class="mb-5">
    <%= render "current_context", game: @game %>
  </div>

  <h4 class="text-center mb-0 mt-3">PLAYERS</h4>
  <% if @game.host?(current_user) %>
    <div class="grid grid-cols-2 mb-3">
      <%= form_with(scope: :game_user, url: game_users_mute_or_unmute_path(game_id: @game.id), method: :patch) do |form| %>
        <%= form.hidden_field :can_message, value: false %>
        <%= form.submit class: "button w-full text-sm", value: "Mute All" %>
      <% end %>
      <%= form_with(scope: :game_user, url: game_users_mute_or_unmute_path(game_id: @game.id), method: :patch) do |form| %>
        <%= form.hidden_field :can_message, value: true %>
        <%= form.submit class: "button w-full text-sm", value: "Unmute All" %>
      <% end %>
    </div>
  <% end %>
  <%= render "players", game_users: @game.game_users.order(:id), for_host: @game.host?(current_user) %>
<% end %>

<% content_for :loading_modal do %>
  <%= render "/shared/loading_modal", options: { id: "loading-modal" } do %>
    <h3 class="text-lg text-center font-medium leading-6 text-terminal-green" ><%= loading_message %><div class="animate-spin inline-block ml-3">|</div></h3>
  <% end %>
<% end %>