config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  get "setup_tokens/index"
  get "setup_tokens/create"
  get "setup_tokens/delete"

  get "setup", to: "setup#index", as: :setup
  post "setup/save", to: "setup#save", as: :save_setup

  resources :setup_tokens, only: [:index, :create, :destroy]

  resources :users
  get "activate/:code", to: "users#activate", as: :user_activation
  post "users/create-from-activation", to: "users#create_from_activation", as: :users_activation_path

  resources :sessions, only: %i[new create destroy]

  get "games/list", to: "games#list", as: :games_list

  resources :games do
    patch "current-context", to: "games/current_context#update", as: :update_context
    get "current-context/edit", to: "games/current_context#edit", as: :edit_context

    patch "host/online", to: "games/host#online"
    patch "host/offline", to: "games/host#offline"
    patch "host/typing", to: "games/host#typing"
    patch "host/stop-typing", to: "games/host#stop_typing"
  end

  get "games/:id/lobby", to: "games#lobby", as: :game_lobby
  patch "games/:id/join", to: "games#join", as: :join_game

  patch "game_users/:id/online", to: "game_users#online"
  patch "game_users/:id/offline", to: "game_users#offline"
  patch "game_users/:id/typing", to: "game_users#typing"
  patch "game_users/:id/stop-typing", to: "game_users#stop_typing"
  patch "game_users/:id", to: "game_users#update", as: :game_user
  patch "game_users/:game_id/mute-or-unmute", to: "game_users#mute_or_unmute_all_players", as: :game_users_mute_or_unmute

  get "messages", to: "messages#index", as: :messages
  post "messages", to: "messages#create", as: :create_message
  get "messages/create"

  get "signup", to: "users#new", as: :signup
  get "login", to: "sessions#new", as: :login
  get "logout", to: "sessions#destroy", as: :logout

  get "tavern", to: "games#index", as: :tavern

  get "about", to: "about#index"

  get "generate-text", to: "generate_text#text"
end

app/controllers/setup_controller.rb
# frozen_string_literal: true

class SetupController < ApplicationController
  skip_before_action :check_for_setup, only: %w[index save]

  def index; end

  def save
    user = User.new(setup_params.merge({ is_owner: true }))

    respond_to do |format|
      if user.save
        session[:user_id] = user.id
        format.html { redirect_to setup_tokens_path, notice: "#{user.username} is now the owner!" }
      else
        format.html { render :index, notice: "Error Setting Up Owner" }
      end
    end
  end

  private

    def setup_params
      params.require(:setup).permit(:username, :password, :password_confirmation)
    end
end

app/views/setup/index.html.erb
<h3 class="text-center mb-5 text-2xl">Setup Subroutine</h3>

<%= render(NoticeComponent.new(message: notice)) %>

<p class="mt-5 text-xl">Thou art one lucky rapscallion! This be an unconfigured installation of SuperTextAdventure. Enter thine username and password below to becometh the owner.</p>

<p class="mt-5 text-xl">Finders keepers, say we...</p>

<%= form_with(scope: :setup, url: save_setup_path, class:"mt-5 pt-5 border-t-2 border-terminal-green", data: { turbo: "false" }) do |form| %>
  <div>
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.password_field :password, minlength: 10 %>
  </div>

  <div>
    <%= form.label :confirm %>
    <%= form.password_field :password_confirmation, minlength: 10 %>
  </div>

  <div>
    <%= form.submit "Become The Owner", class: "button mt-5 w-full text-center" %>
  </div>
<% end %>


<% content_for :sidebar do %>
  <%= ascii("bricks") %>
<% end %>

app/views/setup/list_tokens.html.erb
<h3 class="text-center my-5 text-2xl">Token Management</h3>

<%= render(NoticeComponent.new(message: notice)) %>

<p class="mb-6">Here you can generate links to send to your friends. This will allow them to create a username and a password and join your game(s).</p>

<%= form_with(model: SetupToken.new) do |f| %>
  <%= f.submit class: "button" %>
<% end %>

<% content_for :sidebar do %>
  <%= ascii("bricks") %>
<% end %>

app/views/setup/setup.html.erb
<div>
  <h1 class="font-bold text-4xl">Setup#setup</h1>
  <p>Find me in app/views/setup/setup.html.erb</p>
</div>